/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_KhachSan;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHẠM T.Vi
 */
public class SDDichVU extends javax.swing.JFrame {

    KetNoiCSDL ks = new KetNoiCSDL();
    DefaultTableModel dfQLKH;
    DefaultTableModel dfThue;
    DefaultTableModel dfSDDV;

    /**
     * Creates new form SDDichVU
     */
    public SDDichVU() {
        initComponents();
        this.setTitle("Sử dụng dịch vụ");
        this.setLocationRelativeTo(null);
        dfQLKH = (DefaultTableModel) this.jTable.getModel();
        dfThue = (DefaultTableModel) this.JTableThue.getModel();
        dfSDDV = (DefaultTableModel) this.jtableSDDV.getModel();
        HienThiCSDLDV();
        HienThiCSDLSDDV();
    }
    public boolean KiemtraMaSoTonTai(String ma) {
        try {
            String ql = "select * from SDDichVu where MaSD ='" + ma + "'";
            ResultSet rs = ks.statement.executeQuery(ql);
            if (rs.next()) {
                return true;
            } else {
                return false;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return false;
    }

    private void HienThiCSDLDV() {
        String sql = ("select *from DichVu");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfQLKH.setRowCount(0);
            while (ks.resultset.next()) {
                String ma = ks.resultset.getString("MaDV");
                String ten = ks.resultset.getString("TenDV");
                Double giaTien = ks.resultset.getDouble("GiaTien");
                Vector<Object> vec = new Vector<Object>();
                vec.add(ma);
                vec.add(ten);
                vec.add(giaTien);
                dfQLKH.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SDDichVU.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void HienThiCSDLSDDV() {
        String sql = ("select *from SDDICHVU");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfSDDV.setRowCount(0);
            while (ks.resultset.next()) {
                String maSD = ks.resultset.getString("MaSD");
                String maThue = ks.resultset.getString("MaThue");
                String maDV = ks.resultset.getString("MaDV");
                Date ngaySD = ks.resultset.getDate("NgaySD");
                Double giaTien = ks.resultset.getDouble("DonGia");

                Vector<Object> vec = new Vector<Object>();
                vec.add(maSD);
                vec.add(maThue);
                vec.add(maDV);
                vec.add(ngaySD);
                vec.add(giaTien);
                dfSDDV.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SDDichVU.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableThue = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableSDDV = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaSD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaThue = new javax.swing.JTextField();
        txtMaDV = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtNgaySD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        pnThem = new javax.swing.JButton();
        pnXoa = new javax.swing.JButton();
        pnSua = new javax.swing.JButton();
        pnThoat = new javax.swing.JButton();
        pnLuu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Millon Dollar Hotel");
        jPanel1.add(jLabel9);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        JTableThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thuê", "Mã Phòng", "Ngày vào", "Mã KH", "Mã NV", "Đặt cọc", "Ngày Ra"
            }
        ));
        JTableThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableThueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTableThue);

        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jtableSDDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SD", "Mã Thuê", "Mã DV", "Ngày SD", "Đơn Giá"
            }
        ));
        jtableSDDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableSDDVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtableSDDV);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Sử Dụng dịch vụ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Thuê Phòng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 687, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mã sử dụng: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mã DV:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mã Thuê: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ngày SD:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Đơn Giá:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txtNgaySD)
                            .addComponent(txtMaThue)
                            .addComponent(txtMaSD)
                            .addComponent(txtMaDV))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaySD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40))
        );

        jPanel5.add(jPanel4, java.awt.BorderLayout.CENTER);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã DV", "Tên DV", "Giá tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pnThem.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\THEM.png")); // NOI18N
        pnThem.setText("Thêm");
        pnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnThemActionPerformed(evt);
            }
        });

        pnXoa.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\XOA.png")); // NOI18N
        pnXoa.setText("Xóa ");
        pnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnXoaActionPerformed(evt);
            }
        });

        pnSua.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\SUA.png")); // NOI18N
        pnSua.setText("Sửa");
        pnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnSuaActionPerformed(evt);
            }
        });

        pnThoat.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\THOAT.png")); // NOI18N
        pnThoat.setText("Thoát");
        pnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnThoatActionPerformed(evt);
            }
        });

        pnLuu.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\Ok-icon 2.png")); // NOI18N
        pnLuu.setText("Lưu");
        pnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnLuuActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\chonPhong.png")); // NOI18N
        jButton2.setText("Thuê phòng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\coin-add-icon.png")); // NOI18N
        jButton1.setText("In hóa đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(pnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(58, 58, 58)
                .addComponent(pnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(pnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int row = this.jTable.getSelectedRow();
          this.txtMaDV.setText((String)jTable.getValueAt(row, 0));
          this.txtDonGia.setText(jTable.getValueAt(row, 2)+ "");
    }//GEN-LAST:event_jTableMouseClicked

    private void pnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnThemActionPerformed
        // TODO add your handling code here:
        txtMaDV.setText("");
        txtMaSD.setText("");
        txtMaThue.setText("");
        txtDonGia.setText("");
        txtNgaySD.setText("");
        txtMaSD.requestFocus();
    }//GEN-LAST:event_pnThemActionPerformed

    private void pnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnXoaActionPerformed
        // TODO add your handling code here:
        try {
            String sqlDelete = "Delete from SDDICHVU where MaSD = '" + txtMaSD.getText() + "'";
            int x = ks.statement.executeUpdate(sqlDelete);
            if (x >= 1) {
                HienThiCSDLSDDV();
            }
            try {

            } catch (Exception ex) {

            }
        } catch (SQLException ex) {
            Logger.getLogger(DichVu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnXoaActionPerformed

    private void pnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnSuaActionPerformed
        // TODO add your handling code here:
        try {
            String sqlUpdate = "Update SDDichVu set MaThue = N'" + txtMaThue.getText() + "'" + ",MaDV = '" + txtMaDV.getText() + "'" + ",NgaySD = '" + txtNgaySD.getText() + "'  where MaSD = '" + txtMaSD.getText() + "'";
               String cn_DonGia = "exec CN_DONGIA_SDDV";
            int y = ks.statement.executeUpdate(cn_DonGia);
            int x = ks.statement.executeUpdate(sqlUpdate);
            if (x >= 1  || y >= 1) {
              HienThiCSDLSDDV();
            }
            try {

            } catch (Exception ex) {

            }
        } catch (SQLException ex) {
            Logger.getLogger(SDDichVU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnSuaActionPerformed

    private void pnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnThoatActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null, "Bạn muốn thoát không?",
                "thoát", JOptionPane.YES_NO_CANCEL_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            new HienThiMenu().setVisible(true);
            this.dispose();
        } else if (n == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Không thì thôi");
        }
    }//GEN-LAST:event_pnThoatActionPerformed

    private void pnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnLuuActionPerformed
        // TODO add your handling code here:
        if (txtMaDV.getText().isEmpty() || txtMaThue.getText().isEmpty() || txtNgaySD.getText().isEmpty() || txtMaSD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày chọn phòng!!");
        } else {
          
            if (KiemtraMaSoTonTai(txtMaDV.getText())) {
                JOptionPane.showMessageDialog(null, "Đã trung Mã SD");
            } else {
                try {
                    String sqlInsert = "Insert into SDDichVu "
                            + "Values('" + txtMaSD.getText() + "', N'" + txtMaThue.getText() + "' , N'" + txtMaDV.getText() + "', '" + txtNgaySD.getText() + "', '" + txtDonGia.getText() + "' )";
                    String cn_DonGia = "exec CN_DONGIA_SDDV";
                    int x = ks.statement.executeUpdate(sqlInsert);
                    int y = ks.statement.executeUpdate(cn_DonGia);
                    if (x >= 1  || y >= 1) {
                        HienThiCSDLSDDV();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(SDDichVU.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_pnLuuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(txtNgaySD.getText().isEmpty()){
         JOptionPane.showMessageDialog(null, "Vui lòng nhập ngày!!");
        }
        String sql = ("exec Xem_ThuePhong_VaoNgay  '"+ txtNgaySD.getText()+"'");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfThue.setRowCount(0);
            while (ks.resultset.next()) {
                String Mathue = ks.resultset.getString("MaThue");
                String MaP = ks.resultset.getString("MaP");
                Date NgayVao = ks.resultset.getDate("NgayVao");
                String MaKH = ks.resultset.getString("MaKH");
                String MaNV = ks.resultset.getString("MaNV");
                Double DatCoc = ks.resultset.getDouble("DatCoc");
                Date NgayRa = ks.resultset.getDate("NgayRa");
                Vector<Object> vec = new Vector<Object>();
                vec.add(Mathue);
                vec.add(MaP);
                vec.add(NgayVao);
                vec.add(MaKH);
                vec.add(MaNV);
                vec.add(DatCoc);
                vec.add(NgayRa);
                dfThue.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SDDichVU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTableThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableThueMouseClicked
        // TODO add your handling code here:
         int row = this.JTableThue.getSelectedRow();
        this.txtMaThue.setText((String)JTableThue.getValueAt(row, 0));
      
    }//GEN-LAST:event_JTableThueMouseClicked

    private void jtableSDDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableSDDVMouseClicked
        // TODO add your handling code here:
         int row = this.jtableSDDV.getSelectedRow();
        this.txtMaSD.setText((String)jtableSDDV.getValueAt(row, 0));
        this.txtMaThue.setText((String)jtableSDDV.getValueAt(row, 1));
        this.txtMaDV.setText((String)jtableSDDV.getValueAt(row, 2));
        this.txtNgaySD.setText((Date)jtableSDDV.getValueAt(row, 3)+ "");
         this.txtDonGia.setText(jtableSDDV.getValueAt(row, 4)+ "");
    }//GEN-LAST:event_jtableSDDVMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LuuHoaDon t = new LuuHoaDon();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SDDichVU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SDDichVU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SDDichVU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SDDichVU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SDDichVU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableThue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jtableSDDV;
    private javax.swing.JButton pnLuu;
    private javax.swing.JButton pnSua;
    private javax.swing.JButton pnThem;
    private javax.swing.JButton pnThoat;
    private javax.swing.JButton pnXoa;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtMaSD;
    private javax.swing.JTextField txtMaThue;
    private javax.swing.JTextField txtNgaySD;
    // End of variables declaration//GEN-END:variables
}
