/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_KhachSan;

import java.sql.Date;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHẠM T.Vi
 */
public class TatCaCacPhongThue extends javax.swing.JFrame {

        KetNoiCSDL ks = new KetNoiCSDL();
        DefaultTableModel dfThue;
    /**
     * Creates new form TatCaCacPhongThue
     */
    public TatCaCacPhongThue() {
        initComponents();
          this.setTitle("Tất cả các phòng đã thuê");
        this.setLocationRelativeTo(null);
          dfThue = (DefaultTableModel) this.JTableThue.getModel();
        HienThiDL();
    }
    private void HienThiDL(){
       
        String sql = ("select *from THUEPHONG");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfThue.setRowCount(0);
            while (ks.resultset.next()) {
                String Mathue = ks.resultset.getString("MaThue");
                String MaP = ks.resultset.getString("MaP");
                Date NgayVao = ks.resultset.getDate("NgayVao");
                String MaKH = ks.resultset.getString("MaKH");
                String MaNV = ks.resultset.getString("MaNV");
                Double DatCoc = ks.resultset.getDouble("DatCoc");
                Date NgayRa = ks.resultset.getDate("NgayRa");
                Vector<Object> vec = new Vector<Object>();
                vec.add(Mathue);
                vec.add(MaP);
                vec.add(NgayVao);
                vec.add(MaKH);
                vec.add(MaNV);
                vec.add(DatCoc);
                vec.add(NgayRa);
                dfThue.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SDDichVU.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnThemKh = new javax.swing.JButton();
        pnThemKh1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnThoat = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableThue = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Tất cả các phòng đã thuê");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pnThemKh.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\nhanvien.png")); // NOI18N
        pnThemKh.setText("Thông tin nhân viên");
        pnThemKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnThemKhActionPerformed(evt);
            }
        });

        pnThemKh1.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\Users-icon.png")); // NOI18N
        pnThemKh1.setText("Thông tin Khách hàng");
        pnThemKh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnThemKh1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\dichVu_icon.png")); // NOI18N
        jButton1.setText("Sử dụng dich vụ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnThoat.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\THOAT.png")); // NOI18N
        pnThoat.setText("Thoát");
        pnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnThoatActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\HeThongThongTin\\DoANQL_KhachSan\\src\\Img\\arrow-return-180-left-icon.png")); // NOI18N
        jButton2.setText("Trở lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThemKh1)
                .addGap(32, 32, 32)
                .addComponent(pnThemKh)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(pnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnThoat)
                    .addComponent(jButton2)
                    .addComponent(pnThemKh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThemKh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        JTableThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Thuê", "Mã Phòng", "Ngày vào", "Mã KH", "Mã NV", "Đặt cọc", "Ngày Ra"
            }
        ));
        JTableThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableThueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTableThue);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTableThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableThueMouseClicked
        // TODO add your handling code here:
      

    }//GEN-LAST:event_JTableThueMouseClicked

    private void pnThemKhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnThemKhActionPerformed
        // TODO add your handling code here:
        NhanVien tt = new NhanVien();
        tt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnThemKhActionPerformed

    private void pnThemKh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnThemKh1ActionPerformed
        // TODO add your handling code here:
        ThongTinKhachHang t = new ThongTinKhachHang();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnThemKh1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SDDichVU dv = new SDDichVU();
        dv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnThoatActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(null, "Bạn muốn thoát không?",
                "thoát", JOptionPane.YES_NO_CANCEL_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            new HienThiMenu().setVisible(true);
            this.dispose();
        } else if (n == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Không thì thôi");
        }
    }//GEN-LAST:event_pnThoatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ThuePhong t = new ThuePhong();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TatCaCacPhongThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TatCaCacPhongThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TatCaCacPhongThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TatCaCacPhongThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TatCaCacPhongThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableThue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pnThemKh;
    private javax.swing.JButton pnThemKh1;
    private javax.swing.JButton pnThoat;
    // End of variables declaration//GEN-END:variables
}
