/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QL_KhachSan;

import java.sql.Date;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PHẠM T.Vi
 */
public class TimKiem extends javax.swing.JDialog {
KetNoiCSDL ks = new KetNoiCSDL();
   DefaultTableModel dfQLNV;
    DefaultTableModel dfQLPhong;
    DefaultTableModel dfQLKH;
     DefaultTableModel dfQLDV;
    /**
     * Creates new form TimKiem
     */
    public TimKiem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Tìm kiếm");
        this.setLocationRelativeTo(null);
        dfQLDV = (DefaultTableModel) this.jTable.getModel();
        dfQLKH = (DefaultTableModel) this.jTableKH.getModel();
        dfQLNV = (DefaultTableModel) this.jNV.getModel();
        dfQLPhong = (DefaultTableModel) this.jPhong.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        pnTimDV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        pnDV9 = new javax.swing.JPanel();
        btnTimDV10 = new javax.swing.JButton();
        txtDV = new javax.swing.JTextField();
        btnNewDV9 = new javax.swing.JButton();
        btnTrangChu3 = new javax.swing.JButton();
        pnNhanVien = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jNV = new javax.swing.JTable();
        pnDV7 = new javax.swing.JPanel();
        bnTimKiemNV = new javax.swing.JButton();
        txtNV = new javax.swing.JTextField();
        btnNewDV7 = new javax.swing.JButton();
        btnTrangChu1 = new javax.swing.JButton();
        pnTimPhong = new javax.swing.JPanel();
        pnDV3 = new javax.swing.JPanel();
        bnPhong = new javax.swing.JButton();
        txtPhong = new javax.swing.JTextField();
        btnNewDV3 = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPhong = new javax.swing.JTable();
        pnTimKH = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableKH = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnDV8 = new javax.swing.JPanel();
        bnKhachHang = new javax.swing.JButton();
        txtTimKH = new javax.swing.JTextField();
        btnNewDV8 = new javax.swing.JButton();
        btnTrangChu2 = new javax.swing.JButton();
        pnKH = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabbed.setForeground(new java.awt.Color(0, 51, 51));
        tabbed.setToolTipText("");
        tabbed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Thông Tin Dịch Vụ");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã DV", "Tên DV", "Giá Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        btnTimDV10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimDV10.setForeground(new java.awt.Color(0, 102, 255));
        btnTimDV10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Search-icon.png"))); // NOI18N
        btnTimDV10.setText("Tìm Kiếm");
        btnTimDV10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimDV10ActionPerformed(evt);
            }
        });

        btnNewDV9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewDV9.setForeground(new java.awt.Color(0, 102, 255));
        btnNewDV9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-icon.png"))); // NOI18N
        btnNewDV9.setText("New");
        btnNewDV9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDV9ActionPerformed(evt);
            }
        });

        btnTrangChu3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTrangChu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Home-icon.png"))); // NOI18N
        btnTrangChu3.setText("Trang Chủ");
        btnTrangChu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDV9Layout = new javax.swing.GroupLayout(pnDV9);
        pnDV9.setLayout(pnDV9Layout);
        pnDV9Layout.setHorizontalGroup(
            pnDV9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnTimDV10)
                .addGap(62, 62, 62)
                .addComponent(txtDV, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNewDV9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnDV9Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(btnTrangChu3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDV9Layout.setVerticalGroup(
            pnDV9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV9Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnDV9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimDV10)
                    .addComponent(txtDV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewDV9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangChu3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnTimDVLayout = new javax.swing.GroupLayout(pnTimDV);
        pnTimDV.setLayout(pnTimDVLayout);
        pnTimDVLayout.setHorizontalGroup(
            pnTimDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimDVLayout.createSequentialGroup()
                .addGroup(pnTimDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTimDVLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnTimDVLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnDV9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTimDVLayout.setVerticalGroup(
            pnTimDVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimDVLayout.createSequentialGroup()
                .addComponent(pnDV9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        tabbed.addTab("Tìm Kiếm Dịch Vụ", new javax.swing.ImageIcon(getClass().getResource("/Img/DichVuTimKiem.png")), pnTimDV); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Thông Tin Nhân Viên");

        jNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ và tên NV", "Ngày Sinh", "Địa chỉ", "SĐT"
            }
        ));
        jNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jNV);

        bnTimKiemNV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bnTimKiemNV.setForeground(new java.awt.Color(0, 102, 255));
        bnTimKiemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Search-icon.png"))); // NOI18N
        bnTimKiemNV.setText("Tìm Kiếm");
        bnTimKiemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnTimKiemNVActionPerformed(evt);
            }
        });

        btnNewDV7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewDV7.setForeground(new java.awt.Color(0, 102, 255));
        btnNewDV7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-icon.png"))); // NOI18N
        btnNewDV7.setText("New");
        btnNewDV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDV7ActionPerformed(evt);
            }
        });

        btnTrangChu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTrangChu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Home-icon.png"))); // NOI18N
        btnTrangChu1.setText("Trang Chủ");
        btnTrangChu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDV7Layout = new javax.swing.GroupLayout(pnDV7);
        pnDV7.setLayout(pnDV7Layout);
        pnDV7Layout.setHorizontalGroup(
            pnDV7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bnTimKiemNV)
                .addGap(62, 62, 62)
                .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnNewDV7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnDV7Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(btnTrangChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDV7Layout.setVerticalGroup(
            pnDV7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnDV7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnTimKiemNV)
                    .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewDV7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addComponent(pnDV7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addComponent(pnDV7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        tabbed.addTab("Tim Kiếm Nhân Viên", new javax.swing.ImageIcon(getClass().getResource("/Img/NhanVienVien.png")), pnNhanVien); // NOI18N

        bnPhong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bnPhong.setForeground(new java.awt.Color(0, 102, 255));
        bnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Search-icon.png"))); // NOI18N
        bnPhong.setText("Tìm Kiếm");
        bnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnPhongActionPerformed(evt);
            }
        });

        btnNewDV3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewDV3.setForeground(new java.awt.Color(0, 102, 255));
        btnNewDV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-icon.png"))); // NOI18N
        btnNewDV3.setText("New");
        btnNewDV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDV3ActionPerformed(evt);
            }
        });

        btnTrangChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Home-icon.png"))); // NOI18N
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDV3Layout = new javax.swing.GroupLayout(pnDV3);
        pnDV3.setLayout(pnDV3Layout);
        pnDV3Layout.setHorizontalGroup(
            pnDV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bnPhong)
                .addGap(62, 62, 62)
                .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnNewDV3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnDV3Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDV3Layout.setVerticalGroup(
            pnDV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnDV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnPhong)
                    .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewDV3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Thông Tin Phòng");

        jPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Giá Thuê", "Mã Loại"
            }
        ));
        jPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPhongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jPhong);

        javax.swing.GroupLayout pnTimPhongLayout = new javax.swing.GroupLayout(pnTimPhong);
        pnTimPhong.setLayout(pnTimPhongLayout);
        pnTimPhongLayout.setHorizontalGroup(
            pnTimPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDV3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTimPhongLayout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimPhongLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        pnTimPhongLayout.setVerticalGroup(
            pnTimPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimPhongLayout.createSequentialGroup()
                .addComponent(pnDV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        tabbed.addTab("Tìm Kiếm Phòng", new javax.swing.ImageIcon(getClass().getResource("/Img/New-room-icon.png")), pnTimPhong); // NOI18N

        jTableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Họ và tên Khách Hàng", "Ngày Sinh", "Địa chỉ", "SĐT"
            }
        ));
        jTableKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKHMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableKH);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Thông Tin Khách Hàng");

        bnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bnKhachHang.setForeground(new java.awt.Color(0, 102, 255));
        bnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Search-icon.png"))); // NOI18N
        bnKhachHang.setText("Tìm Kiếm");
        bnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnKhachHangActionPerformed(evt);
            }
        });

        txtTimKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKHActionPerformed(evt);
            }
        });

        btnNewDV8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNewDV8.setForeground(new java.awt.Color(0, 102, 255));
        btnNewDV8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New-icon.png"))); // NOI18N
        btnNewDV8.setText("New");
        btnNewDV8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDV8ActionPerformed(evt);
            }
        });

        btnTrangChu2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTrangChu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Home-icon.png"))); // NOI18N
        btnTrangChu2.setText("Trang Chủ");
        btnTrangChu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDV8Layout = new javax.swing.GroupLayout(pnDV8);
        pnDV8.setLayout(pnDV8Layout);
        pnDV8Layout.setHorizontalGroup(
            pnDV8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(bnKhachHang)
                .addGap(62, 62, 62)
                .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(btnNewDV8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnDV8Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(btnTrangChu2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDV8Layout.setVerticalGroup(
            pnDV8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDV8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnDV8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnKhachHang)
                    .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewDV8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrangChu2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnTimKHLayout = new javax.swing.GroupLayout(pnTimKH);
        pnTimKH.setLayout(pnTimKHLayout);
        pnTimKHLayout.setHorizontalGroup(
            pnTimKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addComponent(pnDV8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTimKHLayout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnTimKHLayout.setVerticalGroup(
            pnTimKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKHLayout.createSequentialGroup()
                .addComponent(pnDV8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tabbed.addTab("Tìm Kiếm Khách Hàng", new javax.swing.ImageIcon(getClass().getResource("/Img/User-Group-icon.png")), pnTimKH); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnKHLayout = new javax.swing.GroupLayout(pnKH);
        pnKH.setLayout(pnKHLayout);
        pnKHLayout.setHorizontalGroup(
            pnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        pnKHLayout.setVerticalGroup(
            pnKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(pnKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(pnKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKHMouseClicked
        // TODO add your handling code here:
        int row = this.jTableKH.getSelectedRow();
       
    }//GEN-LAST:event_jTableKHMouseClicked

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        int row = this.jTable.getSelectedRow();
        
    }//GEN-LAST:event_jTableMouseClicked

    private void jNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNVMouseClicked
        // TODO add your handling code here:
        int row = this.jTableKH.getSelectedRow();
      
    }//GEN-LAST:event_jNVMouseClicked

    private void jPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPhongMouseClicked
        // TODO add your handling code here:
        int row = this.jTableKH.getSelectedRow();
       
    }//GEN-LAST:event_jPhongMouseClicked

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        HienThiMenu t = new HienThiMenu();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnTrangChu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu1ActionPerformed
        // TODO add your handling code here:
          HienThiMenu t = new HienThiMenu();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrangChu1ActionPerformed

    private void btnTrangChu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu2ActionPerformed
        // TODO add your handling code here:
          HienThiMenu t = new HienThiMenu();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrangChu2ActionPerformed

    private void btnTrangChu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChu3ActionPerformed
        // TODO add your handling code here:
          HienThiMenu t = new HienThiMenu();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTrangChu3ActionPerformed

    private void btnNewDV8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDV8ActionPerformed
        // TODO add your handling code here:
        txtTimKH.setText("");
        txtTimKH.requestFocus();
        
    }//GEN-LAST:event_btnNewDV8ActionPerformed

    private void btnNewDV9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDV9ActionPerformed
        // TODO add your handling code here:
        txtDV.setText("");
        txtDV.requestFocus();
    }//GEN-LAST:event_btnNewDV9ActionPerformed

    private void btnNewDV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDV7ActionPerformed
        // TODO add your handling code here:
        txtNV.setText("");
        txtNV.requestFocus();
    }//GEN-LAST:event_btnNewDV7ActionPerformed

    private void btnNewDV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDV3ActionPerformed
        // TODO add your handling code here:
        txtPhong.setText("");
        txtPhong.requestFocus();
    }//GEN-LAST:event_btnNewDV3ActionPerformed

    private void btnTimDV10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimDV10ActionPerformed
        // TODO add your handling code here:
        //String sql = ("select *from DichVu where MaDV like '"+txtDV.getText()+"%' or  TenDV like '"+txtDV.getText()+"%'" );
         String sql = ("exec TimKiemDichVu N'"+txtDV.getText()+"'");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfQLDV.setRowCount(0);
            while (ks.resultset.next()) {
                String ma = ks.resultset.getString("MaDV");
                String ten = ks.resultset.getString("TenDV");
                Double giaTien = ks.resultset.getDouble("GiaTien");
                Vector<Object> vec = new Vector<Object>();
                vec.add(ma);
                vec.add(ten);
                vec.add(giaTien);
                dfQLDV.addRow(vec);
            }

        } catch (SQLException ex) {
            Logger.getLogger(QLKhachSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimDV10ActionPerformed

    private void bnTimKiemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnTimKiemNVActionPerformed
        // TODO add your handling code here:
        String sql = ("exec TimKiemNhanVien N'"+txtNV.getText()+"'");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfQLNV.setRowCount(0);
            while (ks.resultset.next()) {
                String ma = ks.resultset.getString("MaNV");
                String ten = ks.resultset.getString("HoTenNV");
                Date ngaySinh = ks.resultset.getDate("NgaySinh");
                String diaC = ks.resultset.getString("DiaChi");
                String sdt = ks.resultset.getString("SDT");
               Vector<Object>  vec = new Vector<Object>();
               vec.add(ma);
               vec.add(ten);
               vec.add(ngaySinh);
               vec.add(diaC);
               vec.add(sdt);
               dfQLNV.addRow(vec);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(QLKhachSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bnTimKiemNVActionPerformed

    private void txtTimKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKHActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKHActionPerformed

    private void bnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnKhachHangActionPerformed
        // TODO add your handling code here:
        String sql = ("exec TimKiemKhachHang N'"+txtTimKH.getText()+"'");
         try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfQLKH.setRowCount(0);
            while (ks.resultset.next()) {
                String ma = ks.resultset.getString("MaKH");
                String ten = ks.resultset.getString("TenKH");
                Date ngaySinh = ks.resultset.getDate("NgaySinh");
                String diaC = ks.resultset.getString("DiaChi");
                String sdt = ks.resultset.getString("SDT");
               Vector<Object>  vec = new Vector<Object>();
               vec.add(ma);
               vec.add(ten);
               vec.add(ngaySinh);
               vec.add(diaC);
               vec.add(sdt);
               dfQLKH.addRow(vec);
            }   
        } catch (SQLException ex) {
            Logger.getLogger(QLKhachSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bnKhachHangActionPerformed

    private void bnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnPhongActionPerformed
        // TODO add your handling code here:
         String sql = ("exec TimKiemPhong N'"+txtPhong.getText()+"'");
        try {
            ks.statement = ks.connection.createStatement();
            ks.resultset = ks.statement.executeQuery(sql);
            dfQLPhong.setRowCount(0);
            while (ks.resultset.next()) {
                String ma = ks.resultset.getString("MaP");
                String ten = ks.resultset.getString("TenP");
                Double giaTien = ks.resultset.getDouble("GiaThue");
                String maL = ks.resultset.getString("MaLoai");
               Vector<Object>  vec = new Vector<Object>();
               vec.add(ma);
               vec.add(ten);
               vec.add(giaTien);
               vec.add(maL);
               dfQLPhong.addRow(vec);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QLKhachSan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bnPhongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TimKiem dialog = new TimKiem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnKhachHang;
    private javax.swing.JButton bnPhong;
    private javax.swing.JButton bnTimKiemNV;
    private javax.swing.JButton btnNewDV3;
    private javax.swing.JButton btnNewDV7;
    private javax.swing.JButton btnNewDV8;
    private javax.swing.JButton btnNewDV9;
    private javax.swing.JButton btnTimDV10;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnTrangChu1;
    private javax.swing.JButton btnTrangChu2;
    private javax.swing.JButton btnTrangChu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable jNV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jPhong;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTableKH;
    private javax.swing.JPanel pnDV3;
    private javax.swing.JPanel pnDV7;
    private javax.swing.JPanel pnDV8;
    private javax.swing.JPanel pnDV9;
    private javax.swing.JPanel pnKH;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnTimDV;
    private javax.swing.JPanel pnTimKH;
    private javax.swing.JPanel pnTimPhong;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTextField txtDV;
    private javax.swing.JTextField txtNV;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtTimKH;
    // End of variables declaration//GEN-END:variables
}
